name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: setup JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          check-latest: true
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: Assemble All Build Variant
        run: ./gradlew :app:assembleAdmin :app:assembleDriver
      - name: Build with Gradle
        run: ./gradlew build
