name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: setup JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          check-latest: true
      - name: Access MAPS_APKI_KEY
        env:
          APOD_API_KEY: ${{ secrets.MAPS_APKI_KEY }}
        run: echo APOD_API_KEY=\"$MAPS_APKI_KEY\" > ./local.properties
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: Assemble All Build Variant
        run: ./gradlew :app:assembleAdmin :app:assembleDriver
      - name: Build with Gradle
        run: ./gradlew build
