name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: setup JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          check-latest: true
      - name: Access Google Maps SDK API KEY
        env:
          MAPS_API_KEY: ${{ secrets.MAPS_API_KEY }}
        run: echo MAPS_API_KEY=$MAPS_API_KEY > ./local.properties
      - name: Access Google Cloud Platform API KEY
        env:
          GCP_API_KEY: ${{ secrets.GCP_API_KEY }}
        run: echo GCP_API_KEY=\"$GCP_API_KEY\" > ./local.properties
      - name: Access Firebase Cloud Messaging API KEY
        env:
          FCM_SERVER_API: ${{ secrets.FCM_SERVER_API }}
        run: echo FCM_SERVER_API=\"$FCM_SERVER_API\" > ./local.properties
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: Assemble All Build Variant
        run: ./gradlew :app:assembleAdmin :app:assembleDriver
      - name: Build with Gradle
        run: ./gradlew build
